moonshotcollective/recruiter.party

packages/dapp/src/components/ProfileCard.tsx, packages/dapp/src/components/layout/Header.tsx, packages/dapp/src/core/helpers.ts, packages/dapp/src/pages/_app.tsx, packages/dapp/src/pages/index.tsx, packages/dapp/src/pages/profile/[id]/index.tsx
It's not perfect but we have something to show.
=> Profile page

packages/dapp/src/components/ProfileCard.tsx, packages/dapp/src/core/helpers.ts, packages/dapp/src/pages/index.tsx, packages/dapp/src/pages/requests.tsx
=> Add Requests page

packages/dapp/src/pages/index.tsx
Small fix on index page on contract uri call.
=> Fix contract uri call

packages/server/.eslintrc.js, packages/server/graphql/resolvers.js, packages/server/graphql/resolvers/mutations/profiles.js, packages/server/graphql/resolvers/queries/profiles.js, packages/server/graphql/schema.js, packages/server/helpers/ceramic.js, packages/server/models/profile.js, packages/server/package.json, packages/server/server.js, packages/server/services/profiles.js
[x] Adds a search field for string search
[x] Fixes linter rules and lints in the backend
[x] Resolve extraneous issues revealed by linter updates
Fixes #16 #17
=> Add fulltext search in GraphQL API 

packages/dapp/package.json, packages/dapp/src/core/constants/index.ts, packages/dapp/src/pages/profile/[id]/index.tsx, yarn.lock
closes #10 
I left the UnlockProfile component for another PR.
You can access a profile page at the url http://localhost:3000/profile/[did]
For example, http://localhost:3000/profile/did:3:kjzl6cwe1jw149z5serhpr3dmdrg5h67bdwe259m2o7z7pn8d7e6cuc0stz7z0s
=> Add profile page

packages/dapp/src/contexts/Web3Provider.tsx
=> Login and logout from server

packages/dapp/src/contexts/Web3Provider.tsx
Set withCredentials in the 3rd parameter on post logout.
=> Fix logout

packages/dapp/src/pages/profile/[id]/index.tsx, packages/dapp/src/types.ts
Closes #32 
- Added optional chaining wherever possible to avoid errors caused by null states.
- Added some type declarations in a new `types.ts` file.
=> Fix TS errors in profile page and add some types

packages/dapp/src/views/editBasicProfile/index.tsx, packages/dapp/src/views/editPublicProfile/index.tsx
=> Add education fields

packages/dapp/src/pages/profile/edit.tsx, packages/dapp/src/views/editBasicProfile/index.tsx, packages/dapp/src/views/editPrivateProfile/index.tsx
Fixes issue #46
I've changed the profile creation workflow to Private profile -> public profile -> basic profile.
Profile creation/edit workflow is about to test yet as we need to add new education and experience fields to the ceramic schema.
=> change profile edit/create workflow

packages/dapp/src/components/Profile/ApproveUnlock.tsx, packages/dapp/src/components/Profile/RecruiterCard.tsx, packages/dapp/src/components/layout/Navbar.tsx, packages/dapp/src/pages/index.tsx, packages/dapp/src/pages/requests.tsx
=> Requests page

packages/dapp/src/contexts/Web3Provider.tsx
Now uses the `authenticated` endpoint response to check cookie data and make signs more scarce.
Fixes #31
=> feat: Improve message signing behaviour

.github/workflows/ci.yaml, packages/dapp/src/components/Profile/ApproveUnlock.tsx, packages/dapp/src/components/Profile/RecruiterCard.tsx, packages/dapp/src/components/Profile/Unlock.tsx, packages/dapp/src/components/custom/ContractFields.tsx, packages/dapp/src/contexts/Web3Provider.tsx, packages/dapp/src/core/ceramic/identity-link.ts, packages/dapp/src/core/ceramic/index.ts, packages/dapp/src/core/hooks/useDebounce.tsx, packages/dapp/src/core/libs/siwe/abnf.ts, packages/dapp/src/core/libs/siwe/client.ts, packages/dapp/src/pages/index.tsx, packages/dapp/src/pages/requests.tsx, packages/dapp/src/styles/customTheme/colors.ts, packages/dapp/src/styles/customTheme/index.ts
=> Add CI for frontend build and lint

packages/dapp/src/pages/profile/edit.tsx, packages/dapp/src/views/editBasicProfile/index.tsx, packages/dapp/src/views/editPrivateProfile/index.tsx, packages/dapp/src/views/editPublicProfile/index.tsx
=> Allow existing user to edit any profile without saving

packages/dapp/src/views/editPublicProfile/index.tsx
=> Populate fetched profile data for experience and education in inputs

packages/dapp/src/views/editPublicProfile/index.tsx
=> Remove `Title` field from PublicProfile page

package.json, packages/dapp/package.json, packages/server/package.json, packages/ui/package.json
- Had to downgrade from Node v16 to v14 everywhere
- Added a build step for the UI package before the dapp package is built
=> Tweak config to deploy frontend on Vercel

.github/workflows/ci.yaml, Procfile, package.json, packages/server/package.json
We need this to deploy the server to Heroku
=> Update procfile and add server start script to the root

packages/dapp/src/pages/index.tsx, packages/dapp/src/views/editBasicProfile/index.tsx, packages/dapp/src/views/editPublicProfile/index.tsx, packages/server/graphql/resolvers/queries/profiles.js, packages/server/graphql/schema.js, packages/server/models/profile.js, packages/server/routes/index.js, packages/server/routes/profiles.js, packages/server/scripts/createNewProfiles.js, packages/server/services/profiles.js
closes #13 
closes #42 
Now, when the user update your public or basic profile, it's saved on MongoDB too.
The home page profiles are loaded from our backend.
Run node scripts/createNewProfiles.js from packages/server to save the current profiles on MongoDB.
=> Save profiles on MongoDB and load home profiles from MongoDB

package.json, packages/dapp/package.json
=> Change node version to >=14

packages/dapp/src/pages/profile/[id]/index.tsx, packages/server/graphql/resolvers/queries/profiles.js, packages/server/graphql/schema.js
Now the basic profile data and the public profile data is getting from our graphQL endpoint and only the private profile is retrieved from Ceramic.
=> Get profile page data from profile graphQL endpoint
